filter_words = [
    "liquid",
    "capsule",
    "extended release multiphase",
    "tablet",
    "solution",
    "drops",
    "powder",
    "powder packet",
    "inhibitors",
    "cream",
    "topical cream",
    "topical",
    "lotion",
    "gel",
    "solid dispersion",
    "dispersion",
    "solid",
    "vial",
    "syringe",
    "spray powder",
    "topical emollients",
    "emolients",
    "applicator",
    "bandage",
    "foam",
    "shampoo",
    "package",
    "combination"
]